# Generated by Django 4.2.2 on 2024-03-11 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_resetpassword_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='size',
        ),
    ]
