# Generated by Django 4.2.2 on 2024-03-15 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_product_colors_remove_product_sizes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='discount_percent',
        ),
    ]
