# Generated by Django 4.2.2 on 2024-03-19 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='description',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='title',
        ),
    ]
