# Generated by Django 4.2.2 on 2024-03-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayStation4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='games_images')),
            ],
        ),
        migrations.CreateModel(
            name='PlayStation5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='games_images')),
            ],
        ),
        migrations.RenameModel(
            old_name='Games',
            new_name='PlayStation3',
        ),
    ]
