# Generated by Django 4.2.2 on 2024-03-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_games3_games4_games5_playstation3_game3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playstation3',
            name='game3',
        ),
        migrations.RemoveField(
            model_name='playstation4',
            name='game4',
        ),
        migrations.RemoveField(
            model_name='playstation5',
            name='game5',
        ),
        migrations.AddField(
            model_name='playstation3',
            name='game3',
            field=models.ManyToManyField(blank=True, null=True, related_name='games3', to='shop.games3'),
        ),
        migrations.AddField(
            model_name='playstation4',
            name='game4',
            field=models.ManyToManyField(blank=True, null=True, related_name='games4', to='shop.games4'),
        ),
        migrations.AddField(
            model_name='playstation5',
            name='game5',
            field=models.ManyToManyField(blank=True, null=True, related_name='games5', to='shop.games5'),
        ),
    ]
