# Generated by Django 4.2.2 on 2024-03-25 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_playstation3_game3_alter_playstation4_game4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playstation3',
            name='game3',
        ),
        migrations.RemoveField(
            model_name='playstation4',
            name='game4',
        ),
        migrations.RemoveField(
            model_name='playstation5',
            name='game5',
        ),
        migrations.AddField(
            model_name='games3',
            name='play_station3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games3', to='shop.playstation3'),
        ),
        migrations.AddField(
            model_name='games4',
            name='play_station4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games3', to='shop.playstation4'),
        ),
        migrations.AddField(
            model_name='games5',
            name='play_station5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games3', to='shop.playstation5'),
        ),
    ]
