# Generated by Django 4.2.2 on 2024-03-26 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_playstation3_game3_remove_playstation4_game4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games4',
            name='play_station4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games4', to='shop.playstation4'),
        ),
        migrations.AlterField(
            model_name='games5',
            name='play_station5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games5', to='shop.playstation5'),
        ),
    ]
