# Generated by Django 4.2.2 on 2024-03-31 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_games4_play_station4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games3',
            name='image',
        ),
        migrations.RemoveField(
            model_name='games3',
            name='play_station3',
        ),
        migrations.RemoveField(
            model_name='games4',
            name='image',
        ),
        migrations.RemoveField(
            model_name='games4',
            name='play_station4',
        ),
        migrations.RemoveField(
            model_name='games5',
            name='image',
        ),
        migrations.RemoveField(
            model_name='games5',
            name='play_station5',
        ),
        migrations.CreateModel(
            name='warGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='games_images')),
                ('war_games3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='war_games3', to='shop.games3')),
                ('war_games4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='war_games4', to='shop.games4')),
                ('war_games5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='war_games5', to='shop.games5')),
            ],
        ),
        migrations.CreateModel(
            name='sportGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='games_images')),
                ('sport_games3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_games3', to='shop.games3')),
                ('sport_games4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_games4', to='shop.games4')),
                ('sport_games5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_games5', to='shop.games5')),
            ],
        ),
        migrations.CreateModel(
            name='childGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='games_images')),
                ('child_games3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_games3', to='shop.games3')),
                ('child_games4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_games4', to='shop.games4')),
                ('child_games5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_games5', to='shop.games5')),
            ],
        ),
        migrations.CreateModel(
            name='carGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='games_images')),
                ('car_games3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_games3', to='shop.games3')),
                ('car_games4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_games4', to='shop.games4')),
                ('car_games5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_games5', to='shop.games5')),
            ],
        ),
    ]
