# Generated by Django 4.2.2 on 2024-03-31 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_cargames_car_games3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childgames',
            name='ps3_category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ps3_category', to='shop.playstation3'),
        ),
        migrations.AddField(
            model_name='childgames',
            name='ps4_category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ps4_category', to='shop.playstation4'),
        ),
        migrations.AddField(
            model_name='childgames',
            name='ps5_category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ps5_category', to='shop.playstation5'),
        ),
        migrations.AlterField(
            model_name='games3',
            name='car_games3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_games3', to='shop.cargames'),
        ),
        migrations.AlterField(
            model_name='games3',
            name='sport_games3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_games3', to='shop.sportgames'),
        ),
        migrations.AlterField(
            model_name='games3',
            name='war_games3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='war_games3', to='shop.wargames'),
        ),
        migrations.AlterField(
            model_name='games4',
            name='car_games4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_games4', to='shop.cargames'),
        ),
        migrations.AlterField(
            model_name='games4',
            name='child_games4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_games4', to='shop.childgames'),
        ),
        migrations.AlterField(
            model_name='games4',
            name='sport_games4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_games4', to='shop.sportgames'),
        ),
        migrations.AlterField(
            model_name='games4',
            name='war_games4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='war_games4', to='shop.wargames'),
        ),
        migrations.AlterField(
            model_name='games5',
            name='car_games5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_games5', to='shop.cargames'),
        ),
        migrations.AlterField(
            model_name='games5',
            name='child_games5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_games5', to='shop.childgames'),
        ),
        migrations.AlterField(
            model_name='games5',
            name='sport_games5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_games5', to='shop.sportgames'),
        ),
        migrations.AlterField(
            model_name='games5',
            name='war_games5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='war_games5', to='shop.wargames'),
        ),
    ]
