# Generated by Django 4.2.2 on 2024-03-31 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_childgames_ps3_category_childgames_ps4_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childgames',
            name='ps3_category',
        ),
        migrations.RemoveField(
            model_name='childgames',
            name='ps4_category',
        ),
        migrations.RemoveField(
            model_name='childgames',
            name='ps5_category',
        ),
    ]
