# Generated by Django 4.2.2 on 2024-03-31 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_games3_ps3_category_alter_games3_ps4_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games3',
            name='ps3_category',
        ),
        migrations.RemoveField(
            model_name='games3',
            name='ps4_category',
        ),
        migrations.RemoveField(
            model_name='games3',
            name='ps5_category',
        ),
        migrations.RemoveField(
            model_name='games4',
            name='ps3_category',
        ),
        migrations.RemoveField(
            model_name='games4',
            name='ps4_category',
        ),
        migrations.RemoveField(
            model_name='games4',
            name='ps5_category',
        ),
        migrations.RemoveField(
            model_name='games5',
            name='ps3_category',
        ),
        migrations.RemoveField(
            model_name='games5',
            name='ps4_category',
        ),
        migrations.RemoveField(
            model_name='games5',
            name='ps5_category',
        ),
        migrations.AddField(
            model_name='cargames',
            name='ps3_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_game_ps3', to='shop.playstation3'),
        ),
        migrations.AddField(
            model_name='cargames',
            name='ps4_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_game_ps4', to='shop.playstation4'),
        ),
        migrations.AddField(
            model_name='cargames',
            name='ps5_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_game_ps5', to='shop.playstation5'),
        ),
        migrations.AddField(
            model_name='childgames',
            name='ps3_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_game_ps3', to='shop.playstation3'),
        ),
        migrations.AddField(
            model_name='childgames',
            name='ps4_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_game_ps4', to='shop.playstation4'),
        ),
        migrations.AddField(
            model_name='childgames',
            name='ps5_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_game_ps5', to='shop.playstation5'),
        ),
        migrations.AddField(
            model_name='sportgames',
            name='ps3_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_game_ps3', to='shop.playstation3'),
        ),
        migrations.AddField(
            model_name='sportgames',
            name='ps4_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_game_ps4', to='shop.playstation4'),
        ),
        migrations.AddField(
            model_name='sportgames',
            name='ps5_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_game_ps5', to='shop.playstation5'),
        ),
        migrations.AddField(
            model_name='wargames',
            name='ps3_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='war_game_ps3', to='shop.playstation3'),
        ),
        migrations.AddField(
            model_name='wargames',
            name='ps4_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='war_game_ps4', to='shop.playstation4'),
        ),
        migrations.AddField(
            model_name='wargames',
            name='ps5_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='war_game_ps5', to='shop.playstation5'),
        ),
    ]
