# Generated by Django 4.2.2 on 2024-04-02 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_remove_games3_ps3_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childgames',
            name='ps3_category',
        ),
        migrations.RemoveField(
            model_name='childgames',
            name='ps4_category',
        ),
        migrations.RemoveField(
            model_name='childgames',
            name='ps5_category',
        ),
        migrations.RemoveField(
            model_name='sportgames',
            name='ps3_category',
        ),
        migrations.RemoveField(
            model_name='sportgames',
            name='ps4_category',
        ),
        migrations.RemoveField(
            model_name='sportgames',
            name='ps5_category',
        ),
        migrations.RemoveField(
            model_name='wargames',
            name='ps3_category',
        ),
        migrations.RemoveField(
            model_name='wargames',
            name='ps4_category',
        ),
        migrations.RemoveField(
            model_name='wargames',
            name='ps5_category',
        ),
        migrations.CreateModel(
            name='warGamesPs5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='games_images')),
                ('ps5_category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='war_game_ps5', to='shop.playstation5')),
            ],
        ),
        migrations.CreateModel(
            name='warGamesPs4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='games_images')),
                ('ps4_category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='war_game_ps4', to='shop.playstation4')),
            ],
        ),
        migrations.CreateModel(
            name='warGamesPs3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='games_images')),
                ('ps3_category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='war_game_ps3', to='shop.playstation3')),
            ],
        ),
        migrations.CreateModel(
            name='sportGamesPs5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='games_images')),
                ('ps5_category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_game_ps5', to='shop.playstation5')),
            ],
        ),
        migrations.CreateModel(
            name='sportGamesPs4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='games_images')),
                ('ps4_category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_game_ps4', to='shop.playstation4')),
            ],
        ),
        migrations.CreateModel(
            name='sportGamesPs3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='games_images')),
                ('ps3_category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_game_ps3', to='shop.playstation3')),
            ],
        ),
        migrations.CreateModel(
            name='childGamesPs5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='games_images')),
                ('ps5_category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_game_ps5', to='shop.playstation5')),
            ],
        ),
        migrations.CreateModel(
            name='childGamesPs4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='games_images')),
                ('ps4_category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_game_ps4', to='shop.playstation4')),
            ],
        ),
        migrations.CreateModel(
            name='childGamesPs3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='games_images')),
                ('ps3_category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_game_ps3', to='shop.playstation3')),
            ],
        ),
        migrations.CreateModel(
            name='carGamesPs5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='games_images')),
                ('ps5_category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_game_ps5', to='shop.playstation5')),
            ],
        ),
        migrations.CreateModel(
            name='carGamesPs4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='games_images')),
                ('ps4_category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_game_ps4', to='shop.playstation4')),
            ],
        ),
        migrations.CreateModel(
            name='carGamesPs3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='games_images')),
                ('ps3_category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_game_ps3', to='shop.playstation3')),
            ],
        ),
        migrations.AlterField(
            model_name='games3',
            name='car_games3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_games3', to='shop.cargamesps3'),
        ),
        migrations.AlterField(
            model_name='games3',
            name='child_games3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_games3', to='shop.childgamesps3'),
        ),
        migrations.AlterField(
            model_name='games3',
            name='sport_games3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_games3', to='shop.sportgamesps3'),
        ),
        migrations.AlterField(
            model_name='games3',
            name='war_games3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='war_games3', to='shop.wargamesps3'),
        ),
        migrations.AlterField(
            model_name='games4',
            name='car_games4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_games4', to='shop.cargamesps4'),
        ),
        migrations.AlterField(
            model_name='games4',
            name='child_games4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_games4', to='shop.childgamesps4'),
        ),
        migrations.AlterField(
            model_name='games4',
            name='sport_games4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_games4', to='shop.sportgamesps4'),
        ),
        migrations.AlterField(
            model_name='games4',
            name='war_games4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='war_games4', to='shop.wargamesps4'),
        ),
        migrations.AlterField(
            model_name='games5',
            name='car_games5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_games5', to='shop.cargamesps5'),
        ),
        migrations.AlterField(
            model_name='games5',
            name='child_games5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_games5', to='shop.childgamesps5'),
        ),
        migrations.AlterField(
            model_name='games5',
            name='sport_games5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_games5', to='shop.sportgamesps5'),
        ),
        migrations.AlterField(
            model_name='games5',
            name='war_games5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='war_games5', to='shop.wargamesps5'),
        ),
        migrations.DeleteModel(
            name='carGames',
        ),
        migrations.DeleteModel(
            name='childGames',
        ),
        migrations.DeleteModel(
            name='sportGames',
        ),
        migrations.DeleteModel(
            name='warGames',
        ),
    ]
