# Generated by Django 4.2.2 on 2024-04-02 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_remove_childgames_ps3_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargamesps3',
            name='ps3_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.playstation3'),
        ),
        migrations.AlterField(
            model_name='cargamesps4',
            name='ps4_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.playstation4'),
        ),
        migrations.AlterField(
            model_name='cargamesps5',
            name='ps5_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.playstation5'),
        ),
        migrations.AlterField(
            model_name='childgamesps3',
            name='ps3_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.playstation3'),
        ),
        migrations.AlterField(
            model_name='childgamesps4',
            name='ps4_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.playstation4'),
        ),
        migrations.AlterField(
            model_name='childgamesps5',
            name='ps5_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.playstation5'),
        ),
        migrations.AlterField(
            model_name='sportgamesps3',
            name='ps3_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.playstation3'),
        ),
        migrations.AlterField(
            model_name='sportgamesps4',
            name='ps4_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.playstation4'),
        ),
        migrations.AlterField(
            model_name='sportgamesps5',
            name='ps5_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.playstation5'),
        ),
        migrations.AlterField(
            model_name='wargamesps3',
            name='ps3_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.playstation3'),
        ),
        migrations.AlterField(
            model_name='wargamesps4',
            name='ps4_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.playstation4'),
        ),
        migrations.AlterField(
            model_name='wargamesps5',
            name='ps5_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.playstation5'),
        ),
    ]
