# Generated by Django 4.2.2 on 2024-04-02 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_games3_car_games3_alter_games3_child_games3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games3',
            name='car_games3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_games3', to='shop.cargamesps3'),
        ),
        migrations.AlterField(
            model_name='games3',
            name='child_games3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_games3', to='shop.childgamesps3'),
        ),
        migrations.AlterField(
            model_name='games3',
            name='sport_games3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_games3', to='shop.sportgamesps3'),
        ),
        migrations.AlterField(
            model_name='games3',
            name='war_games3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='war_games3', to='shop.wargamesps3'),
        ),
        migrations.AlterField(
            model_name='games4',
            name='car_games4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_games4', to='shop.cargamesps4'),
        ),
        migrations.AlterField(
            model_name='games4',
            name='child_games4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_games4', to='shop.childgamesps4'),
        ),
        migrations.AlterField(
            model_name='games4',
            name='sport_games4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_games4', to='shop.sportgamesps4'),
        ),
        migrations.AlterField(
            model_name='games4',
            name='war_games4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='war_games4', to='shop.wargamesps4'),
        ),
        migrations.AlterField(
            model_name='games5',
            name='car_games5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_games5', to='shop.cargamesps5'),
        ),
        migrations.AlterField(
            model_name='games5',
            name='child_games5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_games5', to='shop.childgamesps5'),
        ),
        migrations.AlterField(
            model_name='games5',
            name='sport_games5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_games5', to='shop.sportgamesps5'),
        ),
        migrations.AlterField(
            model_name='games5',
            name='war_games5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='war_games5', to='shop.wargamesps5'),
        ),
    ]
