# Generated by Django 4.2.2 on 2024-04-02 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_alter_games3_car_games3_alter_games3_child_games3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargamesps3',
            name='ps3_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_game_ps3', to='shop.playstation3'),
        ),
        migrations.AlterField(
            model_name='cargamesps4',
            name='ps4_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_game_ps4', to='shop.playstation4'),
        ),
        migrations.AlterField(
            model_name='cargamesps5',
            name='ps5_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_game_ps5', to='shop.playstation5'),
        ),
        migrations.AlterField(
            model_name='childgamesps3',
            name='ps3_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_game_ps3', to='shop.playstation3'),
        ),
        migrations.AlterField(
            model_name='childgamesps4',
            name='ps4_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_game_ps4', to='shop.playstation4'),
        ),
        migrations.AlterField(
            model_name='childgamesps5',
            name='ps5_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_game_ps5', to='shop.playstation5'),
        ),
        migrations.AlterField(
            model_name='sportgamesps3',
            name='ps3_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_game_ps3', to='shop.playstation3'),
        ),
        migrations.AlterField(
            model_name='sportgamesps4',
            name='ps4_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_game_ps4', to='shop.playstation4'),
        ),
        migrations.AlterField(
            model_name='sportgamesps5',
            name='ps5_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_game_ps5', to='shop.playstation5'),
        ),
        migrations.AlterField(
            model_name='wargamesps3',
            name='ps3_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='war_game_ps3', to='shop.playstation3'),
        ),
        migrations.AlterField(
            model_name='wargamesps4',
            name='ps4_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='war_game_ps4', to='shop.playstation4'),
        ),
        migrations.AlterField(
            model_name='wargamesps5',
            name='ps5_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='war_game_ps5', to='shop.playstation5'),
        ),
    ]
