# Generated by Django 4.2.2 on 2024-04-02 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_alter_games3_car_games3_alter_games3_child_games3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games3',
            name='child_games3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.childgamesps3'),
        ),
    ]
