# Generated by Django 4.2.2 on 2024-04-02 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_alter_games3_child_games3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games3',
            name='child_games3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games3_child_games', to='shop.childgamesps3'),
        ),
    ]
