# Generated by Django 4.2.2 on 2024-04-07 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_remove_cargamesps3_car_game_ps3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sportGamesListPs3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='warGamesListPs3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Games4',
            new_name='carGamesListPs3',
        ),
        migrations.RenameModel(
            old_name='Games3',
            new_name='childGamesListPs3',
        ),
        migrations.RemoveField(
            model_name='cargamesps4',
            name='car_game_ps4',
        ),
        migrations.RemoveField(
            model_name='cargamesps5',
            name='car_game_ps5',
        ),
        migrations.RemoveField(
            model_name='childgamesps4',
            name='child_game_ps4',
        ),
        migrations.RemoveField(
            model_name='childgamesps5',
            name='child_game_ps5',
        ),
        migrations.RemoveField(
            model_name='sportgamesps4',
            name='sport_game_ps4',
        ),
        migrations.RemoveField(
            model_name='sportgamesps5',
            name='sport_game_ps5',
        ),
        migrations.RemoveField(
            model_name='wargamesps4',
            name='war_game_ps4',
        ),
        migrations.RemoveField(
            model_name='wargamesps5',
            name='war_game_ps5',
        ),
        migrations.AlterField(
            model_name='sportgamesps3',
            name='sport_game_ps3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.sportgameslistps3'),
        ),
        migrations.AlterField(
            model_name='wargamesps3',
            name='war_game_ps3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.wargameslistps3'),
        ),
    ]
