# Generated by Django 4.2.2 on 2024-04-07 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_sportgameslistps3_wargameslistps3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargamesps4',
            name='ps4_category',
        ),
        migrations.RemoveField(
            model_name='cargamesps5',
            name='ps5_category',
        ),
        migrations.RemoveField(
            model_name='childgamesps4',
            name='ps4_category',
        ),
        migrations.RemoveField(
            model_name='childgamesps5',
            name='ps5_category',
        ),
        migrations.DeleteModel(
            name='Games5',
        ),
        migrations.RemoveField(
            model_name='sportgamesps4',
            name='ps4_category',
        ),
        migrations.RemoveField(
            model_name='sportgamesps5',
            name='ps5_category',
        ),
        migrations.RemoveField(
            model_name='wargamesps4',
            name='ps4_category',
        ),
        migrations.RemoveField(
            model_name='wargamesps5',
            name='ps5_category',
        ),
        migrations.AlterField(
            model_name='cargamesps3',
            name='car_game_ps3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.cargameslistps3'),
        ),
        migrations.DeleteModel(
            name='carGamesPs4',
        ),
        migrations.DeleteModel(
            name='carGamesPs5',
        ),
        migrations.DeleteModel(
            name='childGamesPs4',
        ),
        migrations.DeleteModel(
            name='childGamesPs5',
        ),
        migrations.DeleteModel(
            name='sportGamesPs4',
        ),
        migrations.DeleteModel(
            name='sportGamesPs5',
        ),
        migrations.DeleteModel(
            name='warGamesPs4',
        ),
        migrations.DeleteModel(
            name='warGamesPs5',
        ),
    ]
