# Generated by Django 4.2.2 on 2024-04-07 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_remove_cargamesps4_ps4_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargamesps3',
            name='car_game_ps3',
        ),
        migrations.RemoveField(
            model_name='childgamesps3',
            name='child_game_ps3',
        ),
        migrations.RemoveField(
            model_name='sportgamesps3',
            name='sport_game_ps3',
        ),
        migrations.RemoveField(
            model_name='wargamesps3',
            name='war_game_ps3',
        ),
        migrations.AddField(
            model_name='cargameslistps3',
            name='car_game_ps3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.cargamesps3'),
        ),
        migrations.AddField(
            model_name='childgameslistps3',
            name='child_game_ps3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.childgamesps3'),
        ),
        migrations.AddField(
            model_name='sportgameslistps3',
            name='sport_game_ps3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.sportgamesps3'),
        ),
        migrations.AddField(
            model_name='wargameslistps3',
            name='war_game_ps3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.wargamesps3'),
        ),
    ]
