# Generated by Django 4.2.2 on 2024-04-07 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_remove_cargamesps3_car_game_ps3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargameslistps3',
            name='car_game_ps3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_game_list_ps3', to='shop.cargamesps3'),
        ),
        migrations.AlterField(
            model_name='childgameslistps3',
            name='child_game_ps3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_game_list_ps3', to='shop.childgamesps3'),
        ),
        migrations.AlterField(
            model_name='sportgameslistps3',
            name='sport_game_ps3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_game_list_ps3', to='shop.sportgamesps3'),
        ),
        migrations.AlterField(
            model_name='wargameslistps3',
            name='war_game_ps3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='war_game_list_ps3', to='shop.wargamesps3'),
        ),
    ]
