# Generated by Django 4.2.2 on 2024-04-07 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_alter_cargameslistps3_car_game_ps3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='carGamesPs4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='games_images')),
                ('ps4_category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_game_ps4', to='shop.playstation4')),
            ],
        ),
        migrations.CreateModel(
            name='carGamesPs5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='games_images')),
                ('ps5_category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_game_ps5', to='shop.playstation5')),
            ],
        ),
        migrations.CreateModel(
            name='childGamesPs4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='games_images')),
                ('ps4_category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_game_ps4', to='shop.playstation4')),
            ],
        ),
        migrations.CreateModel(
            name='childGamesPs5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='games_images')),
                ('ps5_category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_game_ps5', to='shop.playstation5')),
            ],
        ),
        migrations.CreateModel(
            name='Games3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('car_games3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.cargamesps3')),
                ('child_games3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.childgamesps3')),
                ('sport_games3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.sportgamesps3')),
                ('war_games3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.wargamesps3')),
            ],
        ),
        migrations.CreateModel(
            name='Games4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('car_games4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.cargamesps4')),
                ('child_games4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.childgamesps4')),
            ],
        ),
        migrations.CreateModel(
            name='Games5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('car_games5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.cargamesps5')),
                ('child_games5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.childgamesps5')),
            ],
        ),
        migrations.CreateModel(
            name='sportGamesPs4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='games_images')),
                ('ps4_category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_game_ps4', to='shop.playstation4')),
            ],
        ),
        migrations.CreateModel(
            name='sportGamesPs5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='games_images')),
                ('ps5_category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_game_ps5', to='shop.playstation5')),
            ],
        ),
        migrations.CreateModel(
            name='warGamesPs4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='games_images')),
                ('ps4_category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='war_game_ps4', to='shop.playstation4')),
            ],
        ),
        migrations.CreateModel(
            name='warGamesPs5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='games_images')),
                ('ps5_category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='war_game_ps5', to='shop.playstation5')),
            ],
        ),
        migrations.RemoveField(
            model_name='childgameslistps3',
            name='child_game_ps3',
        ),
        migrations.RemoveField(
            model_name='sportgameslistps3',
            name='sport_game_ps3',
        ),
        migrations.RemoveField(
            model_name='wargameslistps3',
            name='war_game_ps3',
        ),
        migrations.DeleteModel(
            name='carGamesListPs3',
        ),
        migrations.DeleteModel(
            name='childGamesListPs3',
        ),
        migrations.DeleteModel(
            name='sportGamesListPs3',
        ),
        migrations.DeleteModel(
            name='warGamesListPs3',
        ),
        migrations.AddField(
            model_name='games5',
            name='sport_games5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.sportgamesps5'),
        ),
        migrations.AddField(
            model_name='games5',
            name='war_games5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.wargamesps5'),
        ),
        migrations.AddField(
            model_name='games4',
            name='sport_games4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.sportgamesps4'),
        ),
        migrations.AddField(
            model_name='games4',
            name='war_games4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.wargamesps4'),
        ),
    ]
