# Generated by Django 4.2.2 on 2024-04-07 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_cargamesps4_cargamesps5_childgamesps4_childgamesps5_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games4',
            name='car_games4',
        ),
        migrations.RemoveField(
            model_name='games4',
            name='child_games4',
        ),
        migrations.RemoveField(
            model_name='games4',
            name='sport_games4',
        ),
        migrations.RemoveField(
            model_name='games4',
            name='war_games4',
        ),
        migrations.RemoveField(
            model_name='games5',
            name='car_games5',
        ),
        migrations.RemoveField(
            model_name='games5',
            name='child_games5',
        ),
        migrations.RemoveField(
            model_name='games5',
            name='sport_games5',
        ),
        migrations.RemoveField(
            model_name='games5',
            name='war_games5',
        ),
        migrations.DeleteModel(
            name='Games3',
        ),
        migrations.DeleteModel(
            name='Games4',
        ),
        migrations.DeleteModel(
            name='Games5',
        ),
    ]
